version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    networks:
      - wpsite
    expose:
      - 3306
      - 33060
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - wpsite

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpsite


networks:
  wpsite:
volumes:
  wordpress:
